CREATE USER "BD1" IDENTIFIED BY "BD1";

/* Atribuição de previlégio */
GRANT "CONNECT" TO "BD1";
GRANT "RESOURCE" TO "BD1";
GRANT UNLIMITED TABLESPACE TO "BD1";
GRANT ALTER ANY CLUSTER TO "BD1";
GRANT ALTER SESSION TO "BD1";
GRANT CREATE PROCEDURE TO "BD1";
GRANT CREATE SEQUENCE TO "BD1";
GRANT CREATE TABLE TO "BD1";
GRANT CREATE TRIGGER TO "BD1";
GRANT CREATE VIEW TO "BD1";
ALTER USER "BD1" DEFAULT ROLE ALL;
