import java.text.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceGrafica.java
 *
 * Created on 12/Mai/2011, 2:28:34
 */
/**
 *
 * @author Tweve
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /** Creates new form InterfaceGrafica */
    public InterfaceGrafica() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mediaChegada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        percentagemAF = new javax.swing.JTextField();
        storageAF = new javax.swing.JTextField();
        storageAG = new javax.swing.JTextField();
        mediaAF = new javax.swing.JTextField();
        desvioAF = new javax.swing.JTextField();
        mediaAG = new javax.swing.JTextField();
        desvioAG = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        utilAF = new javax.swing.JProgressBar();
        utilAG = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatorio = new javax.swing.JTextArea();
        tempo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tempoSimulacao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        partilha = new java.awt.Checkbox();

        jLabel3.setText("%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador SCC");

        jLabel1.setText("Média de Chegada:");

        mediaChegada.setText("1.2");
        mediaChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaChegadaActionPerformed(evt);
            }
        });

        jLabel2.setText("Percentagem AF:");

        percentagemAF.setText("20");
        percentagemAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentagemAFActionPerformed(evt);
            }
        });

        storageAF.setText("1");

        storageAG.setText("2");

        mediaAF.setText("4");

        desvioAF.setText("1.5");

        mediaAG.setText("3.5");

        desvioAG.setText("1");

        jButton1.setText("Simular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Storage AF:");

        jLabel5.setText("Storage AG:");

        jLabel6.setText("Média AF:");

        jLabel7.setText("Desvio AF:");

        jLabel8.setText("Média AG:");

        jLabel9.setText("Desvio AG:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel10.setText("Resultados da Simulação:");

        jLabel11.setText("Utilização AF:");

        jLabel12.setText("Utilização AG:");

        relatorio.setColumns(20);
        relatorio.setRows(5);
        jScrollPane1.setViewportView(relatorio);

        tempo.setText("Tempo de Simulacão:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel13.setText("Entrada de Valores:");

        jLabel14.setText("Tempo Simulação:");

        tempoSimulacao.setText("480");
        tempoSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoSimulacaoActionPerformed(evt);
            }
        });

        jLabel15.setText("%");

        partilha.setLabel("Partilha Funcionários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(379, 379, 379))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(desvioAG, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mediaAG, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(desvioAF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mediaAF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(storageAG, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(storageAF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tempoSimulacao)
                                    .addComponent(mediaChegada, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(percentagemAF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15))))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(utilAG, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tempo))
                                        .addComponent(utilAF, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tempoSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(mediaChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(percentagemAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(utilAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(utilAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(storageAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(storageAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(mediaAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(desvioAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(mediaAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(desvioAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(partilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tempo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mediaChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediaChegadaActionPerformed

    private void percentagemAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentagemAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentagemAFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int tempoSimulacao = 0;
        double media = 0;
        double percentAF = 0;
        int storAF = 0;
        int storAG = 0;
        double mediaAF = 0;
        double dvAF = 0;
        double mediaAG = 0;
        double dvAG = 0;
        Boolean partilha = false;

        try {
            tempoSimulacao = Integer.parseInt(this.tempoSimulacao.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Tempo de simulação inválido!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            media = Double.parseDouble(this.mediaChegada.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Média de chegada inválida!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            percentAF = Double.parseDouble(this.percentagemAF.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Percentagem de atendimento financeiro inválida!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            storAF = Integer.parseInt(this.storageAF.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Storage atendimento financeiro inválido!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            storAG = Integer.parseInt(this.storageAG.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Storage atendimento geral inválido!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            mediaAF = Double.parseDouble(this.mediaAF.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Média atendimento financeiro inválida!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            dvAF = Double.parseDouble(this.desvioAF.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Desvio padrão do atendimento financeiro inválido!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            mediaAG = Double.parseDouble(this.mediaAG.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Média atendimento geral inválida!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            dvAG = Double.parseDouble(this.desvioAG.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Desvio padrão do atendimento geral inválido!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        partilha = this.partilha.getState();
        
        Simulador s = new Simulador();
        
        s.setTempoSimulacao(tempoSimulacao);
        s.setMedia_cheg(media);
        s.setPercentagem_servAF(percentAF / 100);
        s.setNumAtendedoresAF(storAF);
        s.setNumAtendedoresAG(storAG);
        s.setMedia_servAF(mediaAF);
        s.setDesvio_servAF(dvAF);
        s.setMedia_servAG(mediaAG);
        s.setDesvio_servAG(dvAG);
        s.setPartilha(partilha);
        
        s.executa();
        
        
        
        DecimalFormat formato = new DecimalFormat("#0.000");
        
        this.utilAF.setValue( (int)Math.round(s.getUtilizacaoAF()*100) );
        this.utilAG.setValue( (int)Math.round(s.getUtilizacaoAG()*100) );
        this.relatorio.setText(s.getRelat());
        this.tempo.setText("Tempo de Simulação: "+ formato.format(s.getInstante()) );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tempoSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoSimulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoSimulacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desvioAF;
    private javax.swing.JTextField desvioAG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mediaAF;
    private javax.swing.JTextField mediaAG;
    private javax.swing.JTextField mediaChegada;
    private java.awt.Checkbox partilha;
    private javax.swing.JTextField percentagemAF;
    private javax.swing.JTextArea relatorio;
    private javax.swing.JTextField storageAF;
    private javax.swing.JTextField storageAG;
    private javax.swing.JLabel tempo;
    private javax.swing.JTextField tempoSimulacao;
    private javax.swing.JProgressBar utilAF;
    private javax.swing.JProgressBar utilAG;
    // End of variables declaration//GEN-END:variables
}
