/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EliminarReservaGUI.java
 *
 * Created on 16/Dez/2011, 19:16:56
 */
package gui;

import biblioteca.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JDialog;

/**
 *
 * @author Aton
 */
public class EliminarReservaGUI extends javax.swing.JFrame  {
    private static DefaultListModel listModel;
    /** Creates new form EliminarReservaGUI */
    public EliminarReservaGUI(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
         
        

        initComponents();
        refreshListRes();
        setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        eliminar = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();

        list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        eliminar.setText("Eliminar Reserva");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        campoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
     int i = list.getSelectedIndex();
        
        if (i == -1){
            JOptionPane.showMessageDialog(this, "Seleccione um livro.");
        }
        else{
                    String isbn = Biblioteca.fifoReservas.get(i).getLivro().getIsbn();
                    
                    for (int j = 0 ;j<Biblioteca.listaLivros.size();j++)
                        if (Biblioteca.listaLivros.get(j).getIsbn().equals(isbn)){
                            Biblioteca.listaLivros.get(j).setDisponivel(Biblioteca.listaLivros.get(j).getDisponivel()+1);
                            Biblioteca.fifoReservas.get(i).getUtente().setNReservas(Biblioteca.fifoReservas.get(i).getUtente().getNReservas()-1);
                        }
                    
                    Biblioteca.fifoReservas.remove(i);
                    
                    this.refreshListRes();
        }
}//GEN-LAST:event_eliminarActionPerformed

private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
ArrayList<String> strings = Biblioteca.searchRByName(campoPesquisa.getText());
        
            list.removeAll();
            listModel.clear();
            for (int i = 0;i<strings.size();i++){
                listModel.addElement(strings.get(i));
            }
        list.setModel(listModel);
}//GEN-LAST:event_pesquisarActionPerformed

private void campoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_campoPesquisaActionPerformed
 public  DefaultListModel  refreshListRes(){
        
      ArrayList<String> strings = Biblioteca.searchR();
        
        listModel = new DefaultListModel();
            for (int i = 0;i<strings.size();i++){
                listModel.addElement(strings.get(i));
            }
        list.setModel(listModel);
        return listModel;
    }
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JButton eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    private javax.swing.JButton pesquisar;
    // End of variables declaration//GEN-END:variables
}
